### ISSUE TITLE
400 from RERUM on create.action is a 200 in TT

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TinyThings#7]
Server returned HTTP response code: 400 for URL: http://devstore.rerum.io/v1/api/create.action (from dev log)

**Comment by thehabes** [comment]
I experience the same behavior sometimes through TPEN_NL and have to sanity check myself against the bodyReponse.code variable, which always passes what RERUM responded even if not as the proxy response code.

This makes me think that there is some sort of race condition around resp.setStatus(code) in the action responses of rerum_server and should be investigated.
